common/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import path
from django.contrib.auth import views as auth_views

# View
from common import views 


urlpatterns = [

    # Posts

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done/'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( success_url='reset/done/'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('config', views.config_user, name='config_user'),
    path('detail', views.detail_user, name='detail_user'),
    path('', views.home, name='home'), 
    path('login', views.login_view, name='login'),
    path('logout',  views.logout_view, name='logout'),
      
]

newhtml/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from common import urls as url_common
from clientes import urls as url_client
from proyectos import urls as url_proyectos




urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(url_common)),
	path('', include(url_client)),
	path('', include(url_proyectos)),
	
 	 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Seebaan Admin"
admin.site.site_title = "Seebaan "
admin.site.index_title = "Bienvenido a Seebaan"

proyectos/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import path
from django.contrib.auth import views as auth_views
from proyectos import views
import csv
from django.http import HttpResponse
from django.contrib.auth.models import User

from proyectos.views import  homeview, search



urlpatterns = [

    # Posts
    path('add_proyecto', views.add_proyecto, name='add_proyecto'),

    path('add_proyecto_cliente/<int:pk>/', views.add_proyecto_cliente, name='add_proyecto_cliente'),
    path('add_tag', views.add_tag, name='add_tag'), 
    path('list_tag', views.list_tag, name='list_tag'),
    path('edit_tag/<int:pk>/', views.edit_tag, name='edit_tag'),
    path('ajax_add_proyecto', views.ajax_add_proyecto, name='ajax_add_proyecto'),
    path('ajax_add_proyecto_cliente', views.ajax_add_proyecto, name='ajax_add_proyecto'),
    path('list_proyecto', views.list_proyecto, name='list_proyecto'),
    path('edit_proyecto/<int:pk>/', views.edit_proyecto, name='edit_proyecto'),
    path('detail_proyecto/<int:pk>/', views.detail_proyecto, name='detail_proyecto'),
    path('tarea_proyecto/<int:pk>/', views.tarea_proyecto, name='tarea_proyecto'),
    path('add_categoria', views.add_categoria, name='add_categoria'),
    path('list_categoria', views.list_categoria, name='list_categoria'),
    path('detail_categoria/<int:pk>/', views.detail_categoria, name='detail_categoria'),
    path('edit_categoria/<int:pk>/', views.edit_categoria, name='edit_categoria'),
    path('add_dis/<int:pk>/', views.add_dis, name='add_dis'),
    path('list_dis', views.list_dis, name='list_dis'),
    path('detail_dis/<int:pk>/', views.detail_dis, name='detail_dis'),
    path('edit_dis/<int:pk>/', views.edit_dis, name='edit_dis'),
    path('add_tarea/<int:pk>/', views.add_tarea, name='add_tarea'),
    path('list_tarea', views.list_tarea, name='list_tarea'),
    path('edit_tarea/<int:pk>/', views.edit_tarea, name='edit_tarea'),
    path('detail_tarea/<int:pk>/', views.detail_tarea, name='detail_tarea'),
    path('add_comentare/<int:pk>/', views.add_comentare, name='add_comentare'),
    path('list_comentare', views.list_comentare, name='list_comentare'),
    path('edit_comentare/<int:pk>/', views.edit_comentare, name='edit_comentare'),
    path('detail_comentare/<int:pk>/', views.detail_comentare, name='detail_comentare'),
    path('add_imagetarea/<int:pk>/', views.add_imagetarea, name='add_imagetarea'),
    path('add_servicio/<int:pk>/', views.add_servicio, name='add_servicio'),
    path('list_servicio', views.list_servicio, name='list_servicio'),
    path('edit_servicio/<int:pk>/', views.edit_servicio, name='edit_servicio'),
    path('detail_servicio/<int:pk>/', views.detail_servicio, name='detail_servicio'),
    path('add_pagopro/<int:pk>/', views.add_pagopro, name='add_pagopro'),
    path('list_pagopro', views.list_pagopro, name='list_pagopro'),
    path('edit_pagopro/<int:pk>/', views.edit_pagopro, name='edit_pagopro'),
    path('detail_pagopro/<int:pk>/', views.detail_pagopro, name='detail_pagopro'),
    path('add_publi/<int:pk>/', views.add_publi, name='add_publi'),
    path('list_publi', views.list_publi, name='list_publi'),
    path('edit_publi/<int:pk>/', views.edit_publi, name='edit_publi'),
    path('detail_publi/<int:pk>/', views.detail_publi, name='detail_publi'),
    path('add_campa/<int:pk>/', views.add_campa, name='add_campa'),
    path('list_campa', views.list_campa, name='list_campa'),
    path('edit_campa/<int:pk>/', views.edit_campa, name='edit_campa'),
    path('detail_campa/<int:pk>/', views.detail_campa, name='detail_campa'),
    path('search/', search.as_view(), name='search'),
    path('homeview/', homeview.as_view(), name='homeview'),
    path('tarea_detail/<int:pk>/<int:estatus>/', views.tarea_detail, name='tarea_detail'),
    path('get_tarea', views.get_tarea, name='get_tarea'),
    path('ajax_edit_tarea/<int:pk>/', views.ajax_edit_tarea, name='ajax_edit_tarea'),
    path('ajax_edit_comentare/<int:pk>/', views.ajax_edit_comentare, name='ajax_edit_comentare'),
    path('ajax_edit_dis/<int:pk>/', views.ajax_edit_dis, name='ajax_edit_dis'), 
    path('ajax_fill_servicio/<int:pk>/', views.ajax_fill_servicio, name='ajax_fill_servicio'),
    path('ajax_edit_pagopro/<int:pk>/', views.ajax_edit_pagopro, name='ajax_edit_pagopro'),
    path('ajax_edit_publi/<int:pk>/', views.ajax_edit_publi, name='ajax_edit_publi'),
    path('ajax_edit_campa/<int:pk>/', views.ajax_edit_campa, name='ajax_edit_campa'),  
    path('ajax_list_comentare/<int:pk>/', views.ajax_list_comentare, name='ajax_list_comentare'), 
    path('ajax_list_campa/<int:pk>/', views.ajax_list_campa, name='ajax_list_campa'), 
    path('export_proyect', views.export_proyect, name='export_proyect'),
    path('export_tarea', views.export_tarea, name='export_tarea'),
    path('export_pagopro', views.export_pagopro, name='export_pagopro'),
    path('ajax_save_campa/<int:pk>/', views.ajax_save_campa, name='ajax_save_campa'),
    path('ajax_save_publi/<int:pk>/', views.ajax_save_publi, name='ajax_save_publi'),
    path('ajax_save_pagopro/<int:pk>/', views.ajax_save_pagopro, name='ajax_save_pagopro'),
    path('ajax_save_servicio/<int:pk>/', views.ajax_save_servicio, name='ajax_save_servicio'),
    path('ajax_save_dis/<int:pk>/', views.ajax_save_dis, name='ajax_save_dis'), 
    path('ajax_save_comentarea/<int:pk>/', views.ajax_save_comentarea, name='ajax_save_comentarea'),
    path('ajax_save_tarea/<int:pk>/', views.ajax_save_tarea, name='ajax_save_tarea'),
    path('ajax_fill_tarea/<int:pk>/', views.ajax_fill_tarea, name='ajax_fill_tarea'), 
    path('ajax_save_fill_tarea/<int:pk>/', views.ajax_save_fill_tarea, name='ajax_save_fill_tarea'),
    path('ajax_save_cometario/', views.ajax_save_cometario, name='ajax_save_cometario'),
    path('imagen/', views.BasicUploadView.as_view(), name='basic_upload'),
    path('ajax_save_fill_servicio/<int:pk>/', views.ajax_save_fill_servicio, name='ajax_save_fill_servicio'), 
    path('ajax_save_fill_pagopro/<int:pk>/', views.ajax_save_fill_pagopro, name='ajax_save_fill_pagopro'), 
    path('ajax_fill_pagopro/<int:pk>/', views.ajax_fill_pagopro, name='ajax_fill_pagopro'),
    path('ajax_save_fill_publi/<int:pk>/', views.ajax_save_fill_publi, name='ajax_save_fill_publi'), 
    path('ajax_fill_publi/<int:pk>/', views.ajax_fill_publi, name='ajax_fill_publi'),
    path('ajax_save_fill_campa/<int:pk>/', views.ajax_save_fill_campa, name='ajax_save_fill_campa'), 
    path('ajax_fill_campa/<int:pk>/', views.ajax_fill_campa, name='ajax_fill_campa'),
    path('detail_propubli/<int:pk>/', views.detail_proyectopubli, name='detail_proyectopubli'),
    path('filtro_tag_proyecto/<int:pk>/', views.filtro_tag_proyecto, name='filtro_tag_proyecto'),
    path('filtro_tag_cliente/<int:pk>/', views.filtro_tag_cliente, name='filtro_tag_cliente'),
    path('ajax_list_filtrotagproyect/<int:pk>/', views.ajax_list_filtrotagproyect, name='ajax_list_filtrotagproyect'), 
    path('ajax_list_filtrotagclient/<int:pk>/', views.ajax_list_filtrotagclient, name='ajax_list_filtrotagclient'),
    path('filtro_tag/<int:pk>/', views.filtro_tag, name='filtro_tag'),

    #
    path('ajax_change_proyect_status/<int:pk>/', views.ajax_change_proyect_status, name='ajax_change_proyect_status'), 
    path('ajax_list_photos/<int:pk>/', views.ajax_list_photos, name='ajax_list_photos'), 
    path('ajax_set_img_pk/<int:pk>/', views.ajax_set_img_pk, name='ajax_set_img_pk'), 

    #
     path('my_projects', views.my_projects, name='my_projects'),

     path('filtro', views.filtro.as_view(), name='filtro'), 



    
    
    

   


]

clientes/models.py
from django.db import models
from django.utils.translation import ugettext as _
#from proyectos.models import Tag

# Create your models here.

from common.models import Perfil
from django.db.models.signals import post_save
from django.dispatch import receiver

import json
import os
from django.shortcuts import get_object_or_404
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

class Estado(models.Model):
    """ Modelo almacenar estado """
    idestado = models.IntegerField(verbose_name=_('ID unico'), blank=True, null=True)
    estado = models.CharField(verbose_name=_('Nombre de estado'), max_length=100)

    def __str__(self):
        return '%s' % self.estado

    class Meta:
        verbose_name = _('Estado')
        verbose_name_plural = _('Estados')
        default_permissions = ('add', 'change', 'delete', 'view')


class Municipio(models.Model):
    """ Modelo almacenar municipio """
    idmunicipio = models.IntegerField(verbose_name=_('ID unico'), blank=True, null=True)
    estado = models.ForeignKey(Estado, verbose_name=_('Estado'), on_delete=models.CASCADE)
    municipio = models.CharField(verbose_name=_('Nombre de municipio'), max_length=100)

    def __str__(self):
        return '%s' % self.municipio

    class Meta:
        verbose_name = _('Municipio')
        verbose_name_plural = _('Municipios')
        default_permissions = ('add', 'change', 'delete', 'view')


class Client(models.Model):
    """ Modelo de cliente """
    empresa = models.CharField(max_length=200, blank=True)
    email_Corporativo = models.CharField(max_length=100, blank=True)
    direccion_empresa = models.CharField(max_length=400, blank=True)

    pais_options = (
        (1, 'México'),
        (2, 'Estados Unidos'),
        (3, 'Colombia'),
        (4, 'Peru'),
        (5, 'Chile'),
        (5, 'España'),
        (5, 'Argentina'),
    )
    pais = models.IntegerField(verbose_name=_('País'), choices=pais_options)
    estado = models.ForeignKey(Estado, verbose_name=_('Estado'), blank=True, null=True,on_delete=models.CASCADE )
    municipio = models.ForeignKey(Municipio, verbose_name=_('Municipio'), blank=True, null=True, on_delete=models.CASCADE)  # poner chained field

    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email_Personal = models.CharField(max_length=100, blank=True)
    telefono = models.CharField(max_length=15, blank=True)
    celular = models.CharField(max_length=15, blank=True)
    date = models.DateField(blank=True, null=True)

    nombre2 = models.CharField(max_length=200, blank=True)
    apellido2 = models.CharField(max_length=200, blank=True)
    email_Personal2 = models.CharField(max_length=100,  blank=True)
    telefono2 = models.CharField(max_length=15, blank=True)
    celular2 = models.CharField(max_length=15, blank=True)
    date2 = models.DateField(blank=True, null=True)

    comentarios = models.TextField(max_length=500, blank=True)
    dominio = models.CharField(max_length=100, blank=True)

    rfc = models.CharField(max_length=100,blank=True)
    razonsocial = models.CharField(max_length=300, blank=True)
    direccion = models.CharField(max_length=400, blank=True)
    correo = models.CharField(max_length=200, blank=True)
    gasto_options = (
        (1, '[D01] - Honorarios médicos, dentales y gastos hospitalarios.'),
        (2, '[D02] - Gastos médicos por incapacidad o discapacidad'),
        (3, '[D03] - Gastos funerales.'),
        (4, '[D04] - Donativos.'),
        (5, '[D05] - Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).'),
        (6, '[D06] - Aportaciones voluntarias al SAR.'),
        (7, '[D07] - Primas por seguros de gastos médicos.'),
        (8, '[D08] - Gastos de transportación escolar obligatoria.'),
        (9, '[D09] - Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.'),
        (10, '[D10] - Pagos por servicios educativos (colegiaturas)'),
        (11, '[G01] - Adquisición de mercancias'),
        (12, '[G02] - Devoluciones, descuentos o bonificaciones'),
        (13, '[G03] - Gastos en general'),
        (14, '[I01] - Construcciones'),
        (15, '[I02] - Mobilario y equipo de oficina por inversiones'),
        (16, '[I03] - Equipo de transporte'),
        (17, '[I04] - Equipo de computo y accesorios'),
        (18, '[I05] - Dados, troqueles, moldes, matrices y herramental'),
        (19, '[I06] - Comunicaciones telefónicas'),
        (20, '[I07] - Comunicaciones satelitales'),
        (21, '[I08] - Otra maquinaria y equipo'),
        (22, '[P01] - Por definir')
    )
    uso_cfdi = models.IntegerField(verbose_name=_('Uso del comprobante'), choices=gasto_options)
    comentario_factura = models.TextField(max_length=1000, blank=True)



    rfc_2 = models.CharField(max_length=100,blank=True)
    razonsocial_2 = models.CharField(max_length=300, blank=True)
    direccion_2 = models.CharField(max_length=400, blank=True)
    correo_2 = models.CharField(max_length=200, blank=True)
    uso_cfdi_2 = models.IntegerField(verbose_name=_('Uso del comprobante'), choices=gasto_options)
    comentario_factura_2 = models.TextField(max_length=1000, blank=True)


    origen_options = (
        (1, 'Google'),
        (2, 'Facebook'),
        (3, 'Yahoo'),
        (4, 'Recomendado'),
        (5, 'Otro'),
    )
    origen = models.IntegerField(verbose_name=_('Origen'), choices=origen_options)
    marca_options = (
        (1, 'Novemp'),
        (2, 'New'),
        (3, 'Youp'),
        (4, 'Markon'),
    )
    marca = models.IntegerField(verbose_name=_('Origen'), choices=marca_options)
    ejecutivo = models.ForeignKey(Perfil, on_delete=models.CASCADE, verbose_name=_('Usuario'))

    #tag = models.ManyToManyField(Tag, blank=True,)
    def __str__(self):
        return '%s' % self.nombre
# Create your models here.



class EstadosJson(models.Model):
    """ Subir json estados desde admin """
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to="static/files")

    def __unicode__(self):
        return self.name


class MunicipiosJson(models.Model):
    """ Subir json municipios desde admin """
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to="static/files")

    def __unicode__(self):
        return self.name


@receiver(post_save, sender=EstadosJson)
def estadojson(sender, instance, **kwargs):
    """ Senal crear estados """
    urlj = BASE_DIR + instance.file.url
    json_data = open(urlj)
    data = json.load(json_data)
    for val in data:
        p, created = Estado.objects.get_or_create(idestado=val['idestado'], estado=val['estado'])
        if created:
            p.save()
    json_data.close()


@receiver(post_save, sender=MunicipiosJson)
def municipiojson(sender, instance, **kwargs):
    """ Senal crear municipios """
    urlj = BASE_DIR + instance.file.url
    json_data = open(urlj)
    data = json.load(json_data)
    for val in data:
        estado = get_object_or_404(Estado, idestado=val['idestado'])
        p, created = Municipio.objects.get_or_create(estado=estado, idmunicipio=val['idm'], municipio=val['municipio'])
        if created:
            p.save()
    json_data.close()

proyectos/templates/add_imagetarea.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'add_imagetarea' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

   {{ formimg }}
                {% if formimg.errors %}
                    <p class="alert alert-danger">{{ formimg.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit" class="btn btn-primary btn-block mt-5">Enviar</button>
            </form>


        </div>
    </div>
</div>

{% endblock %}

proyectos/templates/detail_categoria.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>Detalle</th>
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>{{categorias.nombre}}</td>
                  <td><a href="/edit_categoria/{{categorias.pk}}">Editar</a></td>
                </tr>

              </tbody>
          </div>
{% endblock %}

proyectos/templates/detail_tagclient.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}



<row>
 <h3>Clientes</h3>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre</th>
                  <th>email_Corporativo</th>
                  <th>email_Personal</th>
                  <th>telefono</th>
                  <th>empresa</th> 
                  

                  
                </tr>
              </thead>
              <tbody class="add_clienttag">

                




              </tbody>
            </table>
          </div>

</row>


{% endblock %}


{% block footer %}
<!-- funcion listar cliente-tag  -->
 
<script type="text/javascript">
function listclienttag(){

          $.ajax({
        url: '/ajax_list_filtrotagclient/{{tag.pk}}/',
        type: 'post',
        dataType: 'json',
        contentType: 'application/json',
        data: '1',
        success: function (data) {

        console.log(data);

        var json = $.parseJSON(data);

            for(var i = 0; i < json.length; i++) {

                console.log(json[i]);

                 var data = json[i];

        var nombre = data.nombre
        var email_Corporativo = data.email_Corporativo
        var email_Personal = data.email_Personal 
        var telefono = data.telefono
        var empresa = data.empresa
        var ciudad = data.ciudad
        var comentarios = data.comentarios
        var date = data.date
        var dominio = data.dominio
        
        
  //funcion actualizar
   $('.add_clienttag').append('<tr><td>'+data.nombre+'</td><td>'+data.email_Corporativo+'</td><td>'+data.email_Personal+'</td><td>'+data.telefono+'</td><td>'+data.empresa+'</td></tr>');


                    }
      },

});


}


$(document).ready( function () {
//Tareas comentario--------------------------------------------------------------
        listclienttag();
});
</script>


{% endblock %}

proyectos/templates/edit_campa.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

            
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            
                {% csrf_token %}

   {{ formca }}
                {% if formca.errors %}
                    <p class="alert alert-danger">{{ formca.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit" id="button_update_cam" class="btn btn-primary btn-block mt-5">Enviar</button>
            


        </div>
    </div>
</div>
{% endblock %}

{% block footer %}

<!-- funcion edit rellenar campos  -->
<script type="text/javascript">
$( document ).ready( function () {
    console.log('fill_publi');
function fill_campa(pk){

                        

        $.ajax({
        url: '/ajax_fill_campa/'+pk+'/',
        type: 'post',
        dataType: 'json',
        contentType: 'application/json',
        data: '1',
        success: function (data) {

        
        console.log(data);
        
        var fechaini = data.fechaini;   
        var fechater = data.fechater;
        var inversion = data.inversion;
        var comision = data.comision;
        var comentario = data.comentario;
        var proyecto = data.proyecto
       

         $('#id_fechaini').val(fechaini);
         $('#id_fechater').val(fechater);
         $('#id_inversion').val(inversion);
         $('#id_comision').val(comision);
         $('#id_comentario').val(comentario);
         $('#id_proyecto').val(proyecto);
         
    
  

        },

});    

}
 fill_campa({{campana.pk}});

});

</script>

<script type="text/javascript">
$('#button_update_cam').on('click', function()  {
        var data_form = {
          fechaini: $("#id_fechaini").val(),
            fechater: $("#id_fechater").val(),
            inversion: $("#id_inversion").val(),
            comision:  $("#id_comision").val(),
            comentario:  $("#id_comentarion").val(),
            proyecto:  $("#id_proyecto").val(),
           

           }
            
            // con el id del llenado de servicio 
            //ocupamos el id proyecto para actualizar los datos de tarea
             pk = $("#id_proyecto").val();
           



        $.ajax({
        url: '/ajax_save_fill_campa/'+pk+'/',
        type: 'post',
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data_form),
        success: function (data) {

        console.log(data);
        
        window.location.reload();


  

        },

});    






        });

</script>



{% endblock %}

proyectos/templates/edit_proyecto.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

            
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

   {{ form }}
                {% if form.errors %}
                    <p class="alert alert-danger">{{ form.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit" class="btn btn-primary btn-block mt-5">Enviar</button>
            </form>


        </div>
    </div>
</div>
{% endblock %}

proyectos/templates/edit_tarea.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

            
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            
                {% csrf_token %}

   {{ formta }}
                {% if formta.errors %}
                    <p class="alert alert-danger">{{ formta.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit"  id="tarea_enviar"  class="btn btn-primary btn-block mt-5">Enviar</button>
           


        </div>
    </div>
</div>
{% endblock %}



{% block footer %}
<script type="text/javascript">
//Edit_tarea---------------------------------------------------------------
$('#tarea_enviar').on('click', function()  {
        var data_form = {
            titulo: $("#id_titulo").val(),
            detalles: $("#id_detalles").val(),
            fechav: $("#id_fechav").val(),
            estado: $("#id_estado").val(),
            prioridad: $("#id_prioridad").val(),
            orden: $("#id_orden").val(), 
            owner: $("#id_owner").val(),
        }

        $.ajax({
        url: '/ajax_edit_tarea/{{tarea.pk}}/',
        type: 'post',
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data_form),
        success: function (data) {

        console.log(data);
        

        window.location.reload();
        

  

        },

});    

});   

</script>
{% endblock %}

proyectos/templates/list_proyecto.html
{% extends "base_user.html" %}
{% load static %}
{% load avance %}
{% block head_content %}
<title>Lista de todos los Proyectos</title>
{% endblock %}

{% block titulo %}Lista de todos los Proyectos<div class="ml-auto">
 <form class="form-horizontal" action="{% url 'filtro' %}" method="get">
                           <div class="input-group">

                              <div class="row">
                                 <div class="col-ml-4">
                                 <input name="nombre" class="form-control" type="text" placeholder="Nombre"><span class="input-group-btn">
                                 </div>
                              <div class="col-ml-4">
                              {{form}}
                              </div>
                     <div class="col-ml-4">
                              <input  class="btn btn-secondary" type="submit" placeholder="Filtrar"></span>
                              </div>
                           </div>

                       </div>
                        </form>





<a href="/add_proyecto"><button class="btn btn-secondary btn-sm btn-addp" type="button">Agregar Proyecto</button></div></a>
  {% endblock%}

{% block container %}


       <div class="row">

        {% for proyect in proyectos %}
               <div class="col-xl-4 col-lg-6">
                  <div class="card b">
                     <div class="card-header">
                        <div class="float-right">
                           <div class="badge badge-info">{{proyect.get_estado_display}}</div>
                        </div>
                        <h4 class="m-0">{{proyect.nombre}}</h4><small class="text-muted">Categoría: {{proyect.categoria.nombre}}</small>
                     </div>
                     <div class="card-body">
                        <div class="d-flex align-items-center">
                           <div class="w-100" data-toggle="tooltip" data-title="Health">
                              <div class="progress progress-xs m-0">
                                 <div class="progress-bar bg-warning" style="width:{% avancetag proyect.pk as avancet %} {{avancet | floatformat:2 }}%"></div>
                              </div>
                           </div>
                           <div class="wd-xxs text-right">
                              <div class="text-bold text-muted">{% avancetag proyect.pk as avancet %} {{avancet | floatformat:2 }}%</div>
                           </div>
                        </div>
                     </div>
                     <table class="table">
                        <tbody>
                           <tr>
                              <td><strong>Fecha de Inicio</strong></td>
                              <td>{{proyect.fecha}}</td>
                           </tr>
                           <tr>
                              <td><strong> Cliente:</strong></td>
                               <td>{{proyect.client}}</td>
                           </tr>
                           <tr>
                              <td><strong> Creado por:</strong></td>
                              <td>{{proyect.usuario}}</td>
                           </tr>
                           <tr>
                              
                           </tr>
                        </tbody>
                     </table>
                     <div class="card-footer text-center"><a href="/detail_proyecto/{{proyect.pk}}"><button class="btn btn-secondary" type="button">Administrar Proyecto</button></a></div>
                  </div>
               </div>

               {% endfor %} 



         </div>
{% endblock %}