clientes/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import path


# View
from clientes import views 


urlpatterns = [

    # Clientes
    path('add_client', views.add_client, name='add_client'),
    path('list_client', views.list_client, name='list_client'),


    path('edit_client/<int:pk>/', views.edit_client, name='edit_client'),
    path('detail_client/<int:pk>/', views.detail_client, name='detail_client'),
    path('delete_client/<int:pk>/', views.delete_client, name='delete_client'),
    path('ajax_save_cliente/<int:pk>/', views.ajax_save_cliente, name='ajax_save_cliente'),
    path('ajax_list_cliente/<int:pk>/', views.ajax_list_cliente, name='ajax_list_cliente'),
    path('ajax_edit_cliente/<int:pk>/', views.ajax_edit_cliente, name='ajax_edit_cliente'),
    path('ajax_save_fill_client/<int:pk>/', views.ajax_save_fill_client, name='ajax_save_fill_client'),
    path('ajax_fill_client/<int:pk>/', views.ajax_fill_client, name='ajax_fill_client'),

    path('searchc', views.search_clients.as_view(), name='searchc'), 



    # Ajax
    path('filtros/estados/', views.filtros_estados, name='filtros_estados'),
    path('filtros/municipios/<int:pk>/', views.filtros_municipios, name='filtros_municipios'),

    

    

      
]

common/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.urls import path
from django.contrib.auth import views as auth_views

# View
from common import views 


urlpatterns = [

    # Posts

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url='done/'), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view( success_url='reset/done/'), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('config', views.config_user, name='config_user'),
    path('detail', views.detail_user, name='detail_user'),
    path('', views.home, name='home'), 
    path('login', views.login_view, name='login'),
    path('logout',  views.logout_view, name='logout'),
      
]

newhtml/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from common import urls as url_common
from clientes import urls as url_client
from proyectos import urls as url_proyectos




urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include(url_common)),
	path('', include(url_client)),
	path('', include(url_proyectos)),
	
 	 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Seebaan Admin"
admin.site.site_title = "Seebaan "
admin.site.index_title = "Bienvenido a Seebaan"

clientes/models.py
from django.db import models
from django.utils.translation import ugettext as _
#from proyectos.models import Tag

# Create your models here.

from common.models import Perfil
from django.db.models.signals import post_save
from django.dispatch import receiver

import json
import os
from django.shortcuts import get_object_or_404
BASE_DIR = os.path.dirname(os.path.dirname(__file__))

class Estado(models.Model):
    """ Modelo almacenar estado """
    idestado = models.IntegerField(verbose_name=_('ID unico'), blank=True, null=True)
    estado = models.CharField(verbose_name=_('Nombre de estado'), max_length=100)

    def __str__(self):
        return '%s' % self.estado

    class Meta:
        verbose_name = _('Estado')
        verbose_name_plural = _('Estados')
        default_permissions = ('add', 'change', 'delete', 'view')


class Municipio(models.Model):
    """ Modelo almacenar municipio """
    idmunicipio = models.IntegerField(verbose_name=_('ID unico'), blank=True, null=True)
    estado = models.ForeignKey(Estado, verbose_name=_('Estado'), on_delete=models.CASCADE)
    municipio = models.CharField(verbose_name=_('Nombre de municipio'), max_length=100)

    def __str__(self):
        return '%s' % self.municipio

    class Meta:
        verbose_name = _('Municipio')
        verbose_name_plural = _('Municipios')
        default_permissions = ('add', 'change', 'delete', 'view')


class Client(models.Model):
    """ Modelo de cliente """
    empresa = models.CharField(max_length=200, blank=True)
    email_Corporativo = models.CharField(max_length=100, blank=True)
    direccion_empresa = models.CharField(max_length=400, blank=True)

    pais_options = (
        (1, 'México'),
        (2, 'Estados Unidos'),
        (3, 'Colombia'),
        (4, 'Peru'),
        (5, 'Chile'),
        (5, 'España'),
        (5, 'Argentina'),
    )
    pais = models.IntegerField(verbose_name=_('País'), choices=pais_options)
    estado = models.ForeignKey(Estado, verbose_name=_('Estado'), blank=True, null=True,on_delete=models.CASCADE )
    municipio = models.ForeignKey(Municipio, verbose_name=_('Municipio'), blank=True, null=True, on_delete=models.CASCADE)  # poner chained field

    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email_Personal = models.CharField(max_length=100, blank=True)
    telefono = models.CharField(max_length=15, blank=True)
    celular = models.CharField(max_length=15, blank=True)
    date = models.DateField(blank=True, null=True)

    nombre2 = models.CharField(max_length=200, blank=True)
    apellido2 = models.CharField(max_length=200, blank=True)
    email_Personal2 = models.CharField(max_length=100,  blank=True)
    telefono2 = models.CharField(max_length=15, blank=True)
    celular2 = models.CharField(max_length=15, blank=True)
    date2 = models.DateField(blank=True, null=True)

    comentarios = models.TextField(max_length=500, blank=True)
    dominio = models.CharField(max_length=100, blank=True)

    rfc = models.CharField(max_length=100,blank=True)
    razonsocial = models.CharField(max_length=300, blank=True)
    direccion = models.CharField(max_length=400, blank=True)
    correo = models.CharField(max_length=200, blank=True)
    gasto_options = (
        (1, '[D01] - Honorarios médicos, dentales y gastos hospitalarios.'),
        (2, '[D02] - Gastos médicos por incapacidad o discapacidad'),
        (3, '[D03] - Gastos funerales.'),
        (4, '[D04] - Donativos.'),
        (5, '[D05] - Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).'),
        (6, '[D06] - Aportaciones voluntarias al SAR.'),
        (7, '[D07] - Primas por seguros de gastos médicos.'),
        (8, '[D08] - Gastos de transportación escolar obligatoria.'),
        (9, '[D09] - Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.'),
        (10, '[D10] - Pagos por servicios educativos (colegiaturas)'),
        (11, '[G01] - Adquisición de mercancias'),
        (12, '[G02] - Devoluciones, descuentos o bonificaciones'),
        (13, '[G03] - Gastos en general'),
        (14, '[I01] - Construcciones'),
        (15, '[I02] - Mobilario y equipo de oficina por inversiones'),
        (16, '[I03] - Equipo de transporte'),
        (17, '[I04] - Equipo de computo y accesorios'),
        (18, '[I05] - Dados, troqueles, moldes, matrices y herramental'),
        (19, '[I06] - Comunicaciones telefónicas'),
        (20, '[I07] - Comunicaciones satelitales'),
        (21, '[I08] - Otra maquinaria y equipo'),
        (22, '[P01] - Por definir')
    )
    uso_cfdi = models.IntegerField(verbose_name=_('Uso del comprobante'), choices=gasto_options)
    comentario_factura = models.TextField(max_length=1000, blank=True)



    rfc_2 = models.CharField(max_length=100,blank=True)
    razonsocial_2 = models.CharField(max_length=300, blank=True)
    direccion_2 = models.CharField(max_length=400, blank=True)
    correo_2 = models.CharField(max_length=200, blank=True)
    uso_cfdi_2 = models.IntegerField(verbose_name=_('Uso del comprobante'), choices=gasto_options)
    comentario_factura_2 = models.TextField(max_length=1000, blank=True)


    origen_options = (
        (1, 'Google'),
        (2, 'Facebook'),
        (3, 'Yahoo'),
        (4, 'Recomendado'),
        (5, 'Otro'),
    )
    origen = models.IntegerField(verbose_name=_('Origen'), choices=origen_options)
    marca_options = (
        (1, 'Novemp'),
        (2, 'New'),
        (3, 'Youp'),
        (4, 'Markon'),
    )
    marca = models.IntegerField(verbose_name=_('Origen'), choices=marca_options)
    ejecutivo = models.ForeignKey(Perfil, on_delete=models.CASCADE, verbose_name=_('Usuario'))

    #tag = models.ManyToManyField(Tag, blank=True,)
    def __str__(self):
        return '%s' % self.nombre
# Create your models here.



class EstadosJson(models.Model):
    """ Subir json estados desde admin """
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to="static/files")

    def __unicode__(self):
        return self.name


class MunicipiosJson(models.Model):
    """ Subir json municipios desde admin """
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to="static/files")

    def __unicode__(self):
        return self.name


@receiver(post_save, sender=EstadosJson)
def estadojson(sender, instance, **kwargs):
    """ Senal crear estados """
    urlj = BASE_DIR + instance.file.url
    json_data = open(urlj)
    data = json.load(json_data)
    for val in data:
        p, created = Estado.objects.get_or_create(idestado=val['idestado'], estado=val['estado'])
        if created:
            p.save()
    json_data.close()


@receiver(post_save, sender=MunicipiosJson)
def municipiojson(sender, instance, **kwargs):
    """ Senal crear municipios """
    urlj = BASE_DIR + instance.file.url
    json_data = open(urlj)
    data = json.load(json_data)
    for val in data:
        estado = get_object_or_404(Estado, idestado=val['idestado'])
        p, created = Municipio.objects.get_or_create(estado=estado, idmunicipio=val['idm'], municipio=val['municipio'])
        if created:
            p.save()
    json_data.close()

clientes/templates/detail_client.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}
<title>Detalle de cliente</title>
{% endblock %}


{% block titulo %}Detalle de cliente<div class="ml-auto">
<a href="/add_proyecto_cliente/{{clientes.pk}}"><button class="btn btn-secondary btn-sm btn-addp" type="button">Agregar Proyecto</button></a></div>
  {% endblock%}




{% block container %}
 <div class="row"> <!-- ROW 2-->

   <div class="col-xl-12"><!--  Start colum 6-->
       <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Empresa</th>
                  <th>Estado</th>
                  <th>Ciudad</th>
                  <th>Dominio</th>
                  <th>Comentarios</th>
                  <th>Origen</th>
                  <th>Marca</th>
                  <th>Ejecutivo</th>

                  <th>Editar</th>
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>{{clientes.empresa}}</td>
                  <td>{{clientes.estado}}</td>
                  <td>{{clientes.municipio}}</td>
                  <td>{{clientes.dominio}}</td>
                  <td>{{clientes.comentarios}}</td>

                  <td>{{clientes.origen}}</td>
                  <td>{{clientes.marca}}</td>
                  <td>{{clientes.ejecutivo}}</td>

                   <td><a href="/edit_client/{{clientes.pk}}">Editar</a></td>
                </tr>

              </tbody>

                </table>
          </div>

<h5 class="text-dark"><strong>Contacto Principal</strong></h5>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre(s)</th>
                  <th>Apellido(s)</th>
                  <th>Teléfono</th>
                   <th>Celular</th>
                  <th>Cumpleaños</th>
                  
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>{{clientes.nombre}}</td>
                  <td>{{clientes.apellido}}</td>
                  <td>{{clientes.telefono}}</td>
                  <td>{{clientes.celular}}</td>
                  <td>{{clientes.date}}</td>
                </tr>

              </tbody>

                </table>
          </div>



<h5 class="text-dark"><strong>Contacto Secundario</strong></h5>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre(s)</th>
                  <th>Apellido(s)</th>
                  <th>Teléfono</th>
                   <th>Celular</th>
                  <th>Cumpleaños</th>
                  
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>{{clientes.nombre2}}</td>
                  <td>{{clientes.apellido2}}</td>
                  <td>{{clientes.telefono2}}</td>
                  <td>{{clientes.celular2}}</td>
                  <td>{{clientes.date2}}</td>
                </tr>

              </tbody>

                </table>
          </div>


<h5 class="text-dark"><strong>Facturación</strong></h5>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>RFC</th>
                  <th>Razón Social</th>
                  <th>Dirección</th>
                   <th>Correo</th>
                  <th>Uso CFDI</th>
                  <th>Comentario</th>
                  
                </tr>
              </thead>
              <tbody>

                <tr>
                  <td>{{clientes.rfc}}</td>
                  <td>{{clientes.razonsocial}}</td>
                  <td>{{clientes.direccion}}</td>
                  <td>{{clientes.correo}}</td>
                  <td>{{clientes.uso_cfdi}}</td>
                  <td>{{clientes.comentario_factura}}</td>
                </tr>

              </tbody>

                </table>
          </div>



</div>
<!-- END colum 6-->


   <div class="col-xl-12"><!--  Start colum 6-->
                  <!-- Team messages-->
                  <div class="card card-default">
                     <div class="card-header">
                        <div class="px-2 float-right badge badge-danger">-</div>
                        <div class="card-title">Proyectos</div>
                     </div><!-- START list group-->
                     <div class="list-group slimScrollDiv" data-height="180" data-scrollable="">
                  


                  <div class="tdiscu">
               
{% for proyecto in proyectos %}

 <!-- START list group item-->
                         <a href="/detail_proyecto/{{proyecto.pk}}"><div class="list-group-item list-group-item-action">
                           <div class="media">
                            <div class="media-body text-truncate">
                                
                                 <p class="mb-1 text-sm"><span class="circle bg-danger circle-lg text-left"></span> {{proyecto.nombre}}</p>
                                 <p class="mb-1 text-sm">Monto: ${{proyecto.monto}}</p>
                              </div>
                              <div class="ml-auto"><div class="badge p-1 bg-gray">{{proyecto.get_estado_display}}</div> <small class="text-muted ml-2"> {{proyecto.fecha}}</small></div>
                           </div>
                        </div></a><!-- END list group item-->


              
{% endfor %} 
</div>
                     </div><!-- END list group-->
                     <!-- START card footer-->
                     <div class="card-footer">
                         
                     </div><!-- END card-footer-->
                  </div><!-- End Team messages-->
                   </div><!-- END colum 6-->
           


</div>

{% endblock %}

clientes/templates/edit_client.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

            
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            
                {% csrf_token %}

   {{ form }}
                {% if form.errors %}
                    <p class="alert alert-danger">{{ formcli.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit" id="button_update_client" class="btn btn-primary btn-block mt-5">Enviar</button>
            


        </div>
    </div>
</div>

{% endblock %}


{% block footer %}


<script type="text/javascript">
$('#button_update_client').on('click', function()  {
        var data_form = {
            nombre: $('#id_nombre').val(),
         email_Corporativo: $('#id_email_Corporativo').val(),
         email_Personal: $('#id_email_Personal').val(),
         telefono: $('#id_telefono').val(),
         empresa: $('#id_empresa').val(),
         ciudad: $('#id_ciudad').val(),
         comentarios: $('#id_comentarios').val(),
         date: $('#id_date').val(),
         dominio: $('#id_dominio').val(),
           }
            

        $.ajax({
        url: '/ajax_save_fill_client/{{ cliente.pk }}/',
        type: 'post',
        dataType: 'json',
        contentType: 'application/json',
        data: JSON.stringify(data_form),
        success: function (data) {

        console.log(data);
        
        if(data.success == 1){
            window.location.href = "/detail_client/{{ cliente.pk }}/";
        }


  

        },

});    






        });

</script>



{% endblock %}

clientes/templates/list_client.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}
<title>Lista de Clientes</title>
{% endblock %}

{% block titulo %}Lista de Clientes
<div class="ml-auto">
 <form class="form-horizontal" action="{% url 'searchc' %}" method="get">
                           <div class="input-group">
                              <div class="row">
                                 <div class="col-ml-4">
                                 <input name="data" class="form-control" type="text" placeholder="Buscar..."><span class="input-group-btn">
                                 </div>
                    
                     <div class="col-ml-4">
                              <input  class="btn btn-secondary" type="submit" placeholder="Buscar"></span>
                     </div>

                       </div>
                       </div>
                        </form>





<a href="/add_client"><button class="btn btn-secondary btn-sm btn-addp" type="button">Agregar Cliente</button></div></a>

{% endblock%}

{% block container %}
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre</th>
                 <th>Email Corporativo</th>
                  <th>Empresa</th>
                  <th>Detalle</th>
                </tr>
              </thead>
              <tbody>
{% for client in clientes %}
                <tr>
                  <td>{{client.nombre}}</td>
                  <td>{{client.email_Corporativo}}</td>
                  <td>{{client.empresa}}</td>
                  <td><a href="/detail_client/{{client.pk}}">Ver detalle</a></td>
                </tr>
{% endfor %} 
              </tbody>
          </div>
{% endblock %}

clientes/templates/search.html
{% extends "base_user.html" %}
{% load static %}

{% block head_content %}
<title>Lista de Clientes</title>
{% endblock %}


{% block titulo %}Lista de Clientes
<div class="ml-auto">
 <form class="form-horizontal" action="{% url 'searchc' %}" method="get">
                           <div class="input-group">
                              <div class="row">
                                 <div class="col-ml-4">
                                 <input name="data" class="form-control" type="text" placeholder="Buscar..."><span class="input-group-btn">
                                 </div>
                    
                     <div class="col-ml-4">
                              <input  class="btn btn-secondary" type="submit" placeholder="Buscar"></span>
                     </div>

                       </div>
                       </div>
                        </form>





<a href="/add_client"><button class="btn btn-secondary btn-sm btn-addp" type="button">Agregar Cliente</button></div></a>

{% endblock%}
{% block container %}
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Nombre</th>
                 <th>Email Corporativo</th>
                  <th>Empresa</th>
                  <th>Detalle</th>
                </tr>
              </thead>
              <tbody>
{% for client in object_list %}
                <tr>
                  <td>{{client.nombre}}</td>
                  <td>{{client.email_Corporativo}}</td>
                  <td>{{client.empresa}}</td>
                  <td><a href="/detail_client/{{client.pk}}">Ver detalle</a></td>
                </tr>
{% endfor %} 
              </tbody>
          </div>
{% endblock %}